#!/bin/bash
# Create placeholder icons for PWA
# These will be replaced with proper PNG icons generated by sharp

ICONS_DIR="../public/icons"
cd "$(dirname "$0")"

# Copy SVG as fallback for all sizes
for size in 72 96 128 144 152 192 384 512; do
    cp "$ICONS_DIR/icon.svg" "$ICONS_DIR/icon-${size}x${size}.svg"
    echo "Created placeholder: icon-${size}x${size}.svg"
done

# Copy for special icons
cp "$ICONS_DIR/icon.svg" "$ICONS_DIR/apple-touch-icon.svg"
cp "$ICONS_DIR/icon.svg" "$ICONS_DIR/badge-72.svg"
cp "$ICONS_DIR/icon.svg" "$ICONS_DIR/favicon-32x32.svg"
cp "$ICONS_DIR/icon.svg" "$ICONS_DIR/favicon-16x16.svg"

echo ""
echo "Placeholder icons created!"
echo ""
echo "To generate proper PNG icons, run:"
echo "  cd frontend"
echo "  npm install sharp"
echo "  node scripts/generate-icons.js"
