#!/usr/bin/env python3
"""
Setup Push Notifications - Generate VAPID keys for web push.

Run this script once to set up push notification infrastructure.
The generated keys should be stored in environment variables:
  - VAPID_PUBLIC_KEY: Share with frontend
  - VAPID_PRIVATE_KEY: Keep secret on server
  - VAPID_SUBJECT: Your contact email (mailto:you@example.com)
"""

import json
import os
import sys
from pathlib import Path

try:
    from py_vapid import Vapid
    HAS_VAPID = True
except ImportError:
    HAS_VAPID = False
    print("py_vapid not installed. Installing...")
    os.system(f"{sys.executable} -m pip install py_vapid pywebpush")
    try:
        from py_vapid import Vapid
        HAS_VAPID = True
    except ImportError:
        print("Failed to install py_vapid")
        sys.exit(1)


def generate_vapid_keys():
    """Generate new VAPID key pair."""
    vapid = Vapid()
    vapid.generate_keys()

    # Get keys in the format we need
    private_key = vapid.private_key.private_bytes(
        encoding=vapid.private_key_to_pem().encoding,
        format=vapid.private_key_to_pem().format,
        encryption_algorithm=vapid.private_key_to_pem().encryption_algorithm
    ).decode('utf-8') if hasattr(vapid, 'private_key_to_pem') else None

    # Use simplified key format
    from cryptography.hazmat.primitives import serialization
    private_bytes = vapid.private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    )

    public_bytes = vapid.public_key.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint
    )

    import base64
    public_key_b64 = base64.urlsafe_b64encode(public_bytes).decode('utf-8').rstrip('=')

    return {
        "private_key": private_bytes.decode('utf-8'),
        "public_key": public_key_b64
    }


def main():
    print("=" * 60)
    print("Push Notification Setup for Abdullah Junior")
    print("=" * 60)

    config_dir = Path("config/push_notifications")
    config_dir.mkdir(parents=True, exist_ok=True)

    vapid_file = config_dir / "vapid_keys.json"

    # Check if keys already exist
    if vapid_file.exists():
        print(f"\nVAPID keys already exist at: {vapid_file}")
        response = input("Generate new keys? This will invalidate existing subscriptions. (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing keys.")

            # Show current public key
            with open(vapid_file) as f:
                existing = json.load(f)
                print(f"\nCurrent VAPID Public Key:")
                print(existing.get("public_key", "Not found"))
            return

    print("\nGenerating VAPID keys...")

    try:
        keys = generate_vapid_keys()
    except Exception as e:
        print(f"Error generating keys with py_vapid: {e}")
        print("\nUsing alternative method...")

        # Alternative: Use openssl or generate manually
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.hazmat.backends import default_backend
        from cryptography.hazmat.primitives import serialization
        import base64

        private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
        public_key = private_key.public_key()

        private_bytes = private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        )

        public_bytes = public_key.public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.UncompressedPoint
        )

        public_key_b64 = base64.urlsafe_b64encode(public_bytes).decode('utf-8').rstrip('=')

        keys = {
            "private_key": private_bytes.decode('utf-8'),
            "public_key": public_key_b64
        }

    # Get email for VAPID subject
    email = input("\nEnter contact email for VAPID subject (e.g., admin@example.com): ").strip()
    if not email:
        email = "admin@abdullahjunior.local"

    vapid_config = {
        "sub": f"mailto:{email}",
        "private_key": keys["private_key"],
        "public_key": keys["public_key"]
    }

    # Save to file
    with open(vapid_file, "w") as f:
        json.dump(vapid_config, f, indent=2)

    print(f"\n✅ VAPID keys saved to: {vapid_file}")

    # Create .env.local entry
    env_file = Path(".env.local")
    env_content = f"""
# Push Notification VAPID Keys (generated by setup_push_notifications.py)
VAPID_SUBJECT=mailto:{email}
VAPID_PUBLIC_KEY={keys["public_key"]}
# Note: Private key is stored in config/push_notifications/vapid_keys.json
"""

    print("\n" + "=" * 60)
    print("Add to your .env.local or environment:")
    print("=" * 60)
    print(env_content)

    # Also create frontend env
    frontend_env = Path("frontend/.env.local")
    frontend_content = f"""
# Push Notification VAPID Public Key
NEXT_PUBLIC_VAPID_PUBLIC_KEY={keys["public_key"]}
"""

    print("\nAdd to frontend/.env.local:")
    print(frontend_content)

    # Offer to append
    response = input("\nAppend to .env.local and frontend/.env.local? (Y/n): ")
    if response.lower() != 'n':
        with open(env_file, "a") as f:
            f.write(env_content)
        print(f"Appended to {env_file}")

        with open(frontend_env, "a") as f:
            f.write(frontend_content)
        print(f"Appended to {frontend_env}")

    print("\n" + "=" * 60)
    print("Setup Complete!")
    print("=" * 60)
    print("""
Next steps:
1. Install pywebpush if not already installed:
   pip install pywebpush

2. Start the API server with notification endpoints

3. Open the PWA on your phone and enable notifications

4. Test with:
   curl -X POST http://localhost:8000/api/notifications/test

Your VAPID Public Key:
""")
    print(keys["public_key"])


if __name__ == "__main__":
    main()
